declare function attachScrollListenerToParents(element: any, callback: any): void;
declare function removeScrollListenerFromParents(element: any, callback: any): void;
declare var style: HTMLStyleElement;
declare var xmlns: string;
declare class DlSelect extends HTMLElement {
    loadingScreenTimeouts: any[];
    loadingStartedAt: number;
    optionsWrapper: HTMLDivElement;
    inputWrapper: HTMLSpanElement;
    noMatchesHint: HTMLSpanElement;
    selectedContainer: HTMLSpanElement;
    inputField: HTMLInputElement;
    arrow: Element;
    connectedCallback(): void;
    multiple: boolean;
    isInitialized: boolean;
    setLoadingStatus(): void;
    isLoading: boolean;
    unsetLoadingStatus(): void;
    _tmpValueWhileLoading: any;
    loadOptions(): void;
    removeAllOptions(): void;
    addOption(optionEl: any): void;
    clearFocusedOption(): void;
    _focusedOption: any;
    focusedOption(): any;
    focusOption(option: any): void;
    nextVisibleOptionAfter(option: any): any;
    previousVisibleOptionAfter(option: any): any;
    filterOptions(str: any): void;
    setValue(val: any): void;
    setOption(optionEl: any): boolean;
    selectedOptionEl: any;
    removeOption(optionEl: any, tagEl: any): boolean;
    getDisplayedText(): any;
    getPlaceholderText(): any;
    updatePlaceholderText(): void;
    getValue(): any;
    focus(): void;
    positionOptions: () => void;
    unfocus(): void;
}
declare module "declarativ_forms" {
    function DeclarativForm(attrs: any, onChangeCallback?: any, onCancelCallback?: any, confirmButtonCaption?: any): void;
    class DeclarativForm {
        constructor(attrs: any, onChangeCallback?: any, onCancelCallback?: any, confirmButtonCaption?: any);
        fields: any;
        dom: HTMLDivElement;
        formElement: HTMLFormElement;
        onChangeCallback: any;
        onCancelCallback: any;
        buttons: any;
        initPromises: {};
        allPromises: any[];
        nonEmptyTabs: any;
        onInputChangeSubscribers: any[];
        escHandler: (e: any) => void;
        enterHandler: (e: any) => void;
        hasUpdatedSinceLastCompare(formData: any, includeTab: any): boolean;
        _lastFromUpdatSate: any;
        _lastFromUpdatSateWithoutTab: any;
        updateForm: (arg0: any, arg1: boolean | undefined, arg2: boolean | undefined) => void;
        subscribeOnInput(callback: any): void;
        notifyOnInputSubscribers(formData: any): void;
        updateCalculatedFields(triggerFieldName: any, formData: any): any;
        getHTML: () => string;
        openInModal: (arg0: attr) => any | undefined;
        appendInElement: (arg0: any, arg1: any) => any;
        hide: () => void;
        show: () => void;
        updateTooltips: (sel: any) => void;
        setTooltip: (fieldName: any, text: any, iconContent: any, className: any) => void;
        setTooltipSuccess: (fieldName: any, text: any) => void;
        setTooltipWarning: (fieldName: any, text: any) => void;
        setTooltipError: (fieldName: any, text: any) => void;
        resetTooltip: (fieldName: any) => void;
        resetTooltips: (fieldNames: any) => void;
        updateTabs: () => void;
        setActiveTab: (arg0: string | undefined) => void;
        deleteFromStack: () => void;
        cancelModalIfCancelable: () => void;
        closeModalIfOpen: (arg0: (formData: object) => {}) => void;
        remove: () => void;
        getValues: () => any;
        createModalElement: (attr: any, doNotMount: any) => HTMLDivElement;
    }
    export default DeclarativForm;
}
//# sourceMappingURL=main.d.ts.map